// Regenerates README.md's keyboard-shortcut tables from the key tables that
// actually resolve keys (see src/commands/shortcutDocs.ts), between the
// <!-- shortcuts:start --> / <!-- shortcuts:end --> markers.
//
//   npm run docs:shortcuts          write the block
//   npm run docs:shortcuts -- --check   exit 1 if it is out of date
//
// tests/shortcut-docs.test.ts runs the check, so the README cannot drift.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";
import { dirname, join } from "node:path";
import { buildShortcutDocs } from "../src/commands/shortcutDocs.ts";
import { en } from "../src/i18n/translations/en.ts";

const START = "<!-- shortcuts:start -->";
const END = "<!-- shortcuts:end -->";
const README = join(dirname(fileURLToPath(import.meta.url)), "..", "README.md");

/** Escape the pipe in labels so it cannot break a markdown table cell. */
function cell(text: string): string {
  return text.replace(/\|/g, "\\|");
}

export function renderShortcutMarkdown(): string {
  const lines: string[] = [
    START,
    "<!-- Generated by scripts/gen-shortcut-docs.ts — edit the key tables, not this block. -->",
    "",
  ];
  for (const section of buildShortcutDocs(false)) {
    lines.push(`### ${en[section.titleKey]}`, "");
    if (section.noteKey) lines.push(en[section.noteKey], "");
    lines.push("| Key | Action |", "| --- | --- |");
    for (const row of section.rows) {
      lines.push(`| \`${cell(row.keys)}\` | ${cell(en[row.titleKey] ?? row.titleKey)} |`);
    }
    lines.push("");
  }
  lines.push(END);
  return lines.join("\n");
}

function splice(readme: string, block: string): string {
  const from = readme.indexOf(START);
  const to = readme.indexOf(END);
  if (from < 0 || to < 0) {
    throw new Error(`README.md is missing the ${START} / ${END} markers`);
  }
  return readme.slice(0, from) + block + readme.slice(to + END.length);
}

export function checkReadme(): { ok: boolean; expected: string } {
  const readme = readFileSync(README, "utf8");
  const expected = splice(readme, renderShortcutMarkdown());
  return { ok: readme === expected, expected };
}

// Only act when run directly, so the test can import the helpers. Compare via
// pathToFileURL so a path containing spaces (percent-encoded in import.meta.url)
// still matches — a bare string endsWith would silently no-op there.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const { ok, expected } = checkReadme();
  if (process.argv.includes("--check")) {
    if (!ok) {
      console.error("README shortcut block is out of date — run: npm run docs:shortcuts");
      process.exit(1);
    }
    console.log("README shortcut block is up to date");
  } else {
    if (ok) console.log("README shortcut block already up to date");
    else {
      writeFileSync(README, expected);
      console.log("README shortcut block updated");
    }
  }
}
